language: node_js
node_js:
  - "8"
script:
  - yarn test
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: packages/documentation-website/build/
  keep-history: true
  on:
    branch: master
